// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Gdrive__RootPickerController from "./gdrive/root_picker_controller"
application.register("gdrive--root-picker", Gdrive__RootPickerController)

import BatchableTableController from "./batchable_table_controller"
application.register("batchable-table", BatchableTableController)

import PartialListController from "./partial_list_controller"
application.register("partial-list", PartialListController)

import PaymentController from "./payment_controller"
application.register("payment", PaymentController)
