/*
 * This file is auto-generated by ./bin/rails stimulus:manifest:update
 * Run that command whenever you add a new controller or create them with
 * ./bin/rails generate stimulus controllerName
 */

import {application} from "./application";

import Gdrive__RootPickerController from "./gdrive/root_picker_controller";
application.register("gdrive--root-picker", Gdrive__RootPickerController);

import BatchableTableController from "./batchable_table_controller";
application.register("batchable-table", BatchableTableController);

import PartialListController from "./partial_list_controller";
application.register("partial-list", PartialListController);

import PaymentController from "./payment_controller";
application.register("payment", PaymentController);

import Wiki__MarkdownEditorController from "./wiki/markdown_editor_controller";
application.register("wiki--markdown-editor", Wiki__MarkdownEditorController);

import Communities__SignupActionController from "./communities/signup_action_controller";
application.register("communities--signup-action", Communities__SignupActionController);

import CommunityDeleteController from "./community_delete_controller";
application.register("community-delete", CommunityDeleteController);

import ModalController from "./modal_controller";
application.register("modal", ModalController);

import ConfirmController from "./confirm_controller";
application.register("confirm", ConfirmController);

import MessagingTopupController from "./messaging_topup_controller";
application.register("messaging-topup", MessagingTopupController);

import Subscription__AddressController from "./subscription/address_controller";
application.register("subscription--address", Subscription__AddressController);
