// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Gdrive__RootPickerController from "./gdrive/root_picker_controller"
application.register("gdrive--root-picker", Gdrive__RootPickerController)
