require: rubocop-rails

AllCops:
  TargetRailsVersion: 6.0
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "script/**/*"
    - "tmp/**/*"
    - "uploads/**/*"
    - "vendor/**/*"
    - "**/*.erb"

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Enabled: true
  Max: 110

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true

Metrics/AbcSize:
  Max: 35

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - lib/**/*.rake
    - spec/**/*
    - config/routes.rb
    - config/initializers/simple_form_bootstrap.rb

Metrics/MethodLength:
  Enabled: true
  Max: 15
  Exclude:
    - db/migrate/*.rb

# Was causing errors, not very important
Rails/BulkChangeTable:
  Enabled: false

# We rely on foreign key constraints to raise errors in some cases, instead
# of using restrict_with_exception.
Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/NotNullColumn:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Exclude:
    - "app/controllers/**/*"
    - "app/decorators/**/*"
    - "app/helpers/**/*"
    - "app/policies/**/*"
    - "app/serializers/**/*"
    - "db/migrate/*.rb"

Style/EmptyMethod:
  EnforcedStyle: expanded

# Sometimes using a series of if/unless blocks in parallel structure is good for readability.
Style/GuardClause:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: true
  AllowedMethods:
    - "[]"
    - to
    - not_to
    - require
    - raise
  Exclude:
    - config/initializers/simple_form_bootstrap.rb
    - config/deploy.rb
    - config/deploy/**/*.rb
    - db/migrate/*.rb
    - Gemfile*

Style/StringLiterals:
  EnforcedStyle: double_quotes

Bundler:
  Enabled: true

Rails:
  Enabled: true
