ARG RUBY_VERSION=3.2.2
ARG NODE_VERSION=18.12.1

FROM ruby:$RUBY_VERSION as base

# System deps -- libvps etc
RUN apt-get update -qq && \
    apt-get install -y build-essential libvips software-properties-common npm && \
    apt-get clean &&  \
    rm -rf /var/lib/apt/lists/* /usr/share/doc /usr/share/man

RUN npm install npm@latest -g && \
    npm install n -g && \
    n latest

RUN npm install -g yarn

WORKDIR /opt/gather

COPY Gemfile Gemfile.lock ./
RUN gem install bundler
RUN bundle install

FROM base as dev-base

COPY . ./
# We might need to change this later
COPY deploy/docker/database.yml config/database.yml
