source "https://rubygems.org"

gem "active_model_serializers", "~> 0.9.3"
gem "acts_as_tenant", "~> 0.4"
gem "attribute_normalizer", "~> 1.2"
gem "babosa", "~> 1.0"
gem "bootstrap-kaminari-views", "~> 0.0"
gem "bootstrap-sass", "~> 3.3.5"
gem "browser", "~> 2.5"
gem "cocoon", "~> 1.2"
gem "coffee-rails", "~> 4.1.0"
gem "config", "~> 1.4"
gem "daemons", "~> 1.2"
gem "datetimepicker-rails", git: "https://github.com/zpaulovics/datetimepicker-rails", branch: "master", submodules: true
gem "delayed_job_active_record", "~> 4.1"
gem "devise", "~> 4.2"
gem "diffy", "~> 3.2"
gem "draper", "~> 2.1"
gem "dropzonejs-rails", "~> 0.7"
gem "exception_notification", "~> 4.1"
gem "factory_bot_rails", "~> 4.0"
gem "faker", "~> 1.7"
gem "font-awesome-sass"
gem "hirb", "~> 0.7"
gem "icalendar", "~> 2.0"
gem "inline_svg", "~> 0.6"
gem "jquery-rails", "~> 4.3"
gem "kaminari", "~> 0.16"
gem "momentjs-rails", "~> 2.9", git: "https://github.com/derekprior/momentjs-rails"
gem "omniauth-google-oauth2", "~> 0.2"
gem "paperclip", git: "https://github.com/sassafrastech/paperclip", branch: "tmp_uploads"
gem "pg", "~> 0.18"
gem "phony_rails", "~> 0.12"
gem "pundit", "~> 1.0"
gem "rails-backbone", "~> 1.2"
gem "rails", "~> 4.2.3"
gem "redcarpet", "~> 3.3"
gem "rolify", "~> 4.1"
gem "sass-rails", "~> 5.0"
gem "simple_form", "~> 3.1"
gem "timecop", "~> 0.8"
gem "uglifier", ">= 1.3.0"
gem "whenever", "~> 0.9"

group :development, :test do
  gem "awesome_print", "~> 1.6"
  gem "byebug", "~> 5.0"
  gem "capistrano-bundler", "~> 1.1.2"
  gem "capistrano-passenger", "~> 0.2"
  gem "capistrano-rails", "~> 1.1"
  gem "capistrano-rbenv", "~> 2.1"
  gem "capistrano3-delayed-job", "~> 1.0"
  gem "capybara-screenshot", "~> 1.0"
  gem "capybara", "~> 2.0"
  gem "fix-db-schema-conflicts", "~> 3.0"
  gem "mailcatcher", "~> 0.6"
  gem "poltergeist", "~> 1.0"
  gem "rspec-rails", "~> 3.0"
  gem "selenium-webdriver", "~> 2.0"
  gem "spring", "~> 1.3"
end
