[tools]
gcloud = "latest"
gum = "latest"
node = { version = "18.12.1", postinstall = "corepack enable" }
ruby = "3.2.2"
yq = "latest"

[tasks.setup]
description = "Interactive setup for Gather development environment"
run = "bin/setup"
