# Configures what translations get sent to JS.
# Only those needed should be included to keep download size small.
translations:
  - file: "app/assets/javascripts/i18n/translations.js"
    only: [
      "*.common.*",
      "*.meals/assignments.*",
      "*.datepicker.*",
      "*.timepicker.*",
      "*.password.strength.*",
      "*.errors.messages.doesnt_match",
      "*.dropzone.*",
      "*.batchable_tables.confirmations.*"
    ]
